### ISSUE TITLE
Running multiple instance

### ISSUE THREAD

**Issue by OmeletWithoutEgg** [TIOJ-INFOR-Online-Judge/tioj-judge#4]
Is it ok to run multiple workers on a single host machine (for different tioj sites)?
Can we specify an alternative location of `/tmp/tioj_box`, `/tmp/tioj_submissions`, `/var/lib/tioj-judge` in config file? (I don't know whether I missed any path constants)

**Comment by adrien1018** [comment]
I haven't tested it yet, but changing the value of `kBoxRoot`, `kSubmissionRoot` and `kDataDir` should supposedly work. I will test it and add them to the config file later.
(Using Docker is another workaround.)

**Comment by adrien1018** [comment]
I realized that I need to move testdata paths out of libtioj in order to enable the configuration of testdata location. I will implement it in the next release.

**Comment by adrien1018** [comment]
Added in 2.0.0. Now it is possible to specify different `box_root`, `submission_root` and `testdata_root` in multiple config files to run multiple instances.
